env:
  node: true
extends:
  - eslint:recommended
  - plugin:prettier/recommended
  - plugin:node/recommended
  - plugin:jest/recommended
plugins:
  - prettier
  - node
  - jest
root: true
rules:
  import/extensions: 'off'
  import/prefer-default-export: 'off'
  max-len: 'off'
  curly: 'error'
  object-curly-newline: 'off'
  operator-linebreak: 'off'
  prefer-arrow-callback: 'error'
  prettier/prettier: 'error'
  node/no-unsupported-features/es-syntax: 'off'
  node/no-missing-import: 'off'
  node/no-missing-require: 'off'
  node/shebang: 'off'
  no-param-reassign:
    - error
    - props: true
      ignorePropertyModificationsFor:
        - err # Error decoration
        - obj # .reduce() object
        - pkg # Package instance
        - req
overrides:
  - files:
      - '**/__tests__/**'
      - '**/__mocks__/**'
      - '**/__helpers__/**'
      - '**/*.js'
    env:
      jest: true
    rules:
      import/no-extraneous-dependencies: 'off'
      no-console: 'off'
      no-param-reassign: 'off'
      node/no-extraneous-import: 'off'
      node/no-extraneous-require: 'off'
      node/no-unpublished-import: 'off'
      strict: 'off'
